// <auto-generated />
namespace ProjetoModelo.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addPropertyInClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPropertyInClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201601062112026_addPropertyInClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
